In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [68]:
train = pd.read_csv('./Data/train.csv') 
test = pd.read_csv('./Data/test.csv') 
sample_solution = pd.read_csv('./Data/sample_submission.csv') 
sample_solution['id'] = test['id']

In [5]:
train.info()
print("\n")
test.info()
print("\n")
sample_solution.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  object
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  object
 6   FAVC                            20758 non-null  object
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object
 10  SMOKE                           20758 non-null  object
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  object
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  object
 16  MTRANS                          20758 non-null  object
 17  NObeyesdad                      20758 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 2.9+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13840 entries, 0 to 13839
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              13840 non-null  int64
 1   Gender                          13840 non-null  object
 2   Age                             13840 non-null  float64
 3   Height                          13840 non-null  float64
 4   Weight                          13840 non-null  float64
 5   family_history_with_overweight  13840 non-null  object
 6   FAVC                            13840 non-null  object
 7   FCVC                            13840 non-null  float64
 8   NCP                             13840 non-null  float64
 9   CAEC                            13840 non-null  object
 10  SMOKE                           13840 non-null  object
 11  CH2O                            13840 non-null  float64
 12  SCC                             13840 non-null  object
 13  FAF                             13840 non-null  float64
 14  TUE                             13840 non-null  float64
 15  CALC                            13840 non-null  object
 16  MTRANS                          13840 non-null  object
dtypes: float64(8), int64(1), object(8)
memory usage: 1.8+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13840 entries, 0 to 13839
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          13840 non-null  int64
 1   NObeyesdad  13840 non-null  object
dtypes: int64(1), object(1)
memory usage: 216.4+ KB

In [8]:
sample_solution.head()

      id     NObeyesdad
0  20758  Normal_Weight
1  20759  Normal_Weight
2  20760  Normal_Weight
3  20761  Normal_Weight
4  20762  Normal_Weight

In [7]:
train.head()

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II

In [13]:
print(train['NObeyesdad'].unique())
print("\n")
print(train['MTRANS'].unique())
print("\n")
print(train['CAEC'].unique())
print("\n")
print(train['CALC'].unique())
print("\n")

['Overweight_Level_II' 'Normal_Weight' 'Insufficient_Weight'
 'Obesity_Type_III' 'Obesity_Type_II' 'Overweight_Level_I'
 'Obesity_Type_I']


['Public_Transportation' 'Automobile' 'Walking' 'Motorbike' 'Bike']


['Sometimes' 'Frequently' 'no' 'Always']


['Sometimes' 'no' 'Frequently']

In [30]:
def y_numbering(output:str) -> int:
    if(output == "Normal_Weight"):
        return 0
    if(output == "Insufficient_Weight"):
        return 1
    if(output == "Overweight_Level_I"):
        return 2
    if(output == "Overweight_Level_II"):
        return 3
    if(output == "Obesity_Type_I"):
        return 4
    if(output == "Obesity_Type_II"):
        return 5
    return 6

def is_arg_true(string:str,arg:str) -> bool:
    if(string==arg):
        return 1
    return 0

def yes_or_no_bool(thing:str) -> bool:
    if(thing == "yes"):
        return 1
    return 0

def male_or_female(gender:str) -> bool: 
    if(gender == "Male"):
        return 1
    return 0

def frequency_numbering(freq:str) -> int:
    if(freq =="no"):
        return 0
    if(freq == "Sometimes"):
        return 1
    if(freq == "Frequently"):
        return 2
    return 3

def y_restringing(label:int) -> str: 
    if(label==0):
        return "Normal_Weight"
    if(label==1):
        return "Insufficient_Weight"
    if(label==2):
        return "Overweight_Level_I"
    if(label==3):
        return "Overweight_Level_II"
    if(label==4):
        return "Obesity_Type_I"
    if(label==5):
        return "Obesity_Type_II"
    return "Obesity_Type_III"

In [69]:
#Convert string stuff to labels 
train['usePublicT'] = train['MTRANS']=="Public_Transportation"
train['useCar'] = train['MTRANS']=="Automobile"
train['useBike'] = train['MTRANS']=="Bike"
train['useMotorbike'] = train['MTRANS']=="Motorbike"
train['useFeet'] = train['MTRANS']=="Walking"
train['CAEC'] = train['CAEC'].apply(frequency_numbering)
train['CALC'] = train['CALC'].apply(frequency_numbering)
train['family_history_with_overweight'] = train['family_history_with_overweight'].apply(yes_or_no_bool)
train['FAVC'] = train['FAVC'].apply(yes_or_no_bool)
train['SMOKE'] = train['SMOKE'].apply(yes_or_no_bool)
train['SCC'] = train['SCC'].apply(yes_or_no_bool)
train['Gender'] = train['Gender'].apply(male_or_female)
train['NObeyesdad'] = train['NObeyesdad'].apply(y_numbering)
train.drop('MTRANS',inplace=True,axis=1)
train.drop('id',inplace=True,axis=1)
#print(train['usePublicT'])

In [70]:
test['usePublicT'] = test['MTRANS']=="Public_Transportation"
test['useCar'] = test['MTRANS']=="Automobile"
test['useBike'] = test['MTRANS']=="Bike"
test['useMotorbike'] = test['MTRANS']=="Motorbike"
test['useFeet'] = test['MTRANS']=="Walking"
test['CAEC'] = test['CAEC'].apply(frequency_numbering)
test['CALC'] = test['CALC'].apply(frequency_numbering)
test['family_history_with_overweight'] = test['family_history_with_overweight'].apply(yes_or_no_bool)
test['FAVC'] = test['FAVC'].apply(yes_or_no_bool)
test['SMOKE'] = test['SMOKE'].apply(yes_or_no_bool)
test['SCC'] = test['SCC'].apply(yes_or_no_bool)
test['Gender'] = test['Gender'].apply(male_or_female)
test.drop('MTRANS',inplace=True,axis=1)
test.drop('id',inplace=True,axis=1)

In [71]:
test = np.asarray(test).astype(np.float32)

# Note about the above data I guess

1. 18 columns in the dataset

2. Column that we want to predict is NObeyesdad. 

        --> 7 unique values to predict. 

        i.      Insufficient_Weight

        ii.     Normal_Weight

        iii.    Overweight_Level_I

        iv.     Overweight_Level_II

        v.      Obesity_Type_I

        vi.     Obesity_Type_II

        vii.    Obesity_Type_III    
         
        --> Looks to be a multi-class classification problem. 

3. Method of transportation has 5 unique values

        i.      Public_Transportation

        ii.     Automobile

        iii.    Walking (This one could be pretty significant I would like to assume) 

        iv.     Motorbike

        v.      Bike

In [38]:
correlation_thing = train.corr(method='pearson')
print(correlation_thing)

                                  Gender       Age    Height    Weight  \
Gender                          1.000000  0.066530  0.623507  0.118613
Age                             0.066530  1.000000 -0.011713  0.283381
Height                          0.623507 -0.011713  1.000000  0.416677
Weight                          0.118613  0.283381  0.416677  1.000000
family_history_with_overweight  0.095786  0.261575  0.228137  0.514147
FAVC                            0.021812  0.056848  0.115566  0.228770
FCVC                           -0.312766  0.034414 -0.071546  0.245682
NCP                             0.039468 -0.048479  0.191383  0.095947
CAEC                           -0.046129 -0.151498 -0.069003 -0.337331
SMOKE                           0.063349  0.056006  0.069748  0.040416
CH2O                            0.053298 -0.016325  0.183706  0.317914
SCC                            -0.061442 -0.108855 -0.095923 -0.185116
FAF                             0.238399 -0.192259  0.295278 -0.084845
TUE                             0.058696 -0.296154  0.076433 -0.086471
CALC                           -0.037345  0.070323  0.089138  0.216673
NObeyesdad                     -0.077646  0.342126  0.160523  0.892850
usePublicT                     -0.168146 -0.545798 -0.068578  0.043695
useCar                          0.148765  0.605392  0.054758 -0.002079
useBike                         0.022265  0.006393  0.013701 -0.021761
useMotorbike                    0.015955  0.013754  0.002375 -0.023137
useFeet                         0.062676 -0.078640  0.040525 -0.099298

                                family_history_with_overweight      FAVC  \
Gender                                                0.095786  0.021812
Age                                                   0.261575  0.056848
Height                                                0.228137  0.115566
Weight                                                0.514147  0.228770
family_history_with_overweight                        1.000000  0.152154
FAVC                                                  0.152154  1.000000
FCVC                                                  0.047756  0.006952
NCP                                                   0.044778  0.011522
CAEC                                                 -0.204263 -0.115675
SMOKE                                                 0.018782 -0.016009
CH2O                                                  0.191588  0.039167
SCC                                                  -0.166760 -0.111897
FAF                                                  -0.094414 -0.067030
TUE                                                   0.005762  0.034843
CALC                                                 -0.002330  0.080184
NObeyesdad                                            0.497799  0.218087
usePublicT                                           -0.060354  0.035871
useCar                                                0.102144  0.014370
useBike                                              -0.026278 -0.027491
useMotorbike                                         -0.006291 -0.023162
useFeet                                              -0.088520 -0.118515

                                    FCVC       NCP      CAEC     SMOKE  ...  \
Gender                         -0.312766  0.039468 -0.046129  0.063349  ...
Age                             0.034414 -0.048479 -0.151498  0.056006  ...
Height                         -0.071546  0.191383 -0.069003  0.069748  ...
Weight                          0.245682  0.095947 -0.337331  0.040416  ...
family_history_with_overweight  0.047756  0.044778 -0.204263  0.018782  ...
FAVC                            0.006952  0.011522 -0.115675 -0.016009  ...
FCVC                            1.000000  0.113349  0.010870 -0.012191  ...
NCP                             0.113349  1.000000  0.089957  0.006820  ...
CAEC                            0.010870  0.089957  1.000000  0.019703  ...
SMOKE                          -0.012191  0.006820  0.019703  1.000000  ...
CH2O                            0.101299  0.080949 -0.132820 -0.023475  ...
SCC                             0.022120  0.006633  0.099427  0.017185  ...
FAF                            -0.089822  0.100871  0.092035  0.008374  ...
TUE                            -0.147843  0.067459  0.049646 -0.016093  ...
CALC                            0.128793  0.099421 -0.066821  0.023254  ...
NObeyesdad                      0.281761  0.026897 -0.350794  0.006387  ...
usePublicT                      0.093360 -0.024884  0.013935 -0.023537  ...
useCar                         -0.095624  0.007457 -0.045418  0.019333  ...
useBike                        -0.012134  0.002850  0.014071  0.029815  ...
useMotorbike                    0.006724  0.004866  0.020669  0.026625  ...
useFeet                        -0.006344  0.045570  0.068119 -0.001540  ...

                                     SCC       FAF       TUE      CALC  \
Gender                         -0.061442  0.238399  0.058696 -0.037345
Age                            -0.108855 -0.192259 -0.296154  0.070323
Height                         -0.095923  0.295278  0.076433  0.089138
Weight                         -0.185116 -0.084845 -0.086471  0.216673
family_history_with_overweight -0.166760 -0.094414  0.005762 -0.002330
FAVC                           -0.111897 -0.067030  0.034843  0.080184
FCVC                            0.022120 -0.089822 -0.147843  0.128793
NCP                             0.006633  0.100871  0.067459  0.099421
CAEC                            0.099427  0.092035  0.049646 -0.066821
SMOKE                           0.017185  0.008374 -0.016093  0.023254
CH2O                           -0.031720  0.082932 -0.010654  0.082735
SCC                             1.000000  0.061828 -0.007917  0.000208
FAF                             0.061828  1.000000  0.021213 -0.090076
TUE                            -0.007917  0.021213  1.000000 -0.079790
CALC                            0.000208 -0.090076 -0.079790  1.000000
NObeyesdad                     -0.170217 -0.233109 -0.102639  0.186456
usePublicT                      0.012027 -0.043105  0.150641  0.014137
useCar                         -0.030781 -0.005389 -0.178160 -0.001643
useBike                         0.013323  0.019898 -0.013738  0.008149
useMotorbike                    0.010977  0.007884 -0.012932 -0.020263
useFeet                         0.039124  0.121534  0.055565 -0.030002

                                NObeyesdad  usePublicT    useCar   useBike  \
Gender                           -0.077646   -0.168146  0.148765  0.022265
Age                               0.342126   -0.545798  0.605392  0.006393
Height                            0.160523   -0.068578  0.054758  0.013701
Weight                            0.892850    0.043695 -0.002079 -0.021761
family_history_with_overweight    0.497799   -0.060354  0.102144 -0.026278
FAVC                              0.218087    0.035871  0.014370 -0.027491
FCVC                              0.281761    0.093360 -0.095624 -0.012134
NCP                               0.026897   -0.024884  0.007457  0.002850
CAEC                             -0.350794    0.013935 -0.045418  0.014071
SMOKE                             0.006387   -0.023537  0.019333  0.029815
CH2O                              0.267332    0.059524 -0.071704  0.016424
SCC                              -0.170217    0.012027 -0.030781  0.013323
FAF                              -0.233109   -0.043105 -0.005389  0.019898
TUE                              -0.102639    0.150641 -0.178160 -0.013738
CALC                              0.186456    0.014137 -0.001643  0.008149
NObeyesdad                        1.000000    0.064582 -0.008698 -0.034187
usePublicT                        0.064582    1.000000 -0.917075 -0.079553
useCar                           -0.008698   -0.917075  1.000000 -0.017799
useBike                          -0.034187   -0.079553 -0.017799  1.000000
useMotorbike                     -0.034810   -0.086703 -0.019398 -0.001683
useFeet                          -0.131794   -0.307146 -0.068718 -0.005961

                                useMotorbike   useFeet
Gender                              0.015955  0.062676
Age                                 0.013754 -0.078640
Height                              0.002375  0.040525
Weight                             -0.023137 -0.099298
family_history_with_overweight     -0.006291 -0.088520
FAVC                               -0.023162 -0.118515
FCVC                                0.006724 -0.006344
NCP                                 0.004866  0.045570
CAEC                                0.020669  0.068119
SMOKE                               0.026625 -0.001540
CH2O                                0.007257  0.015921
SCC                                 0.010977  0.039124
FAF                                 0.007884  0.121534
TUE                                -0.012932  0.055565
CALC                               -0.020263 -0.030002
NObeyesdad                         -0.034810 -0.131794
usePublicT                         -0.086703 -0.307146
useCar                             -0.019398 -0.068718
useBike                            -0.001683 -0.005961
useMotorbike                        1.000000 -0.006497
useFeet                            -0.006497  1.000000

[21 rows x 21 columns]

In [80]:
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import tensorflow as tf
Y = train['NObeyesdad']
X = train.copy()

X.drop('NObeyesdad',inplace=True,axis=1)
X = np.asarray(X).astype(np.float32)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)
X_train, Y_train = shuffle(X_train, Y_train)
X_test, Y_test = shuffle(X_test, Y_test)
train_y_categorical = tf.keras.utils.to_categorical(Y_train, num_classes=7)
test_y_categorical = tf.keras.utils.to_categorical(Y_test, num_classes=7)

In [57]:
#tf.config.set_visible_devices([], 'GPU')
#tf.config.list_physical_devices
print(tf.test.is_gpu_available())
#tf.config.list_physical_devices('GPU')

False

In [85]:
model = tf.keras.Sequential()
#model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation=tf.nn.relu, input_shape = (20,)))
model.add(tf.keras.layers.Normalization(axis=-1))
#model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
#model.add(tf.keras.layers.Dropout(0.5))
#model.add(tf.keras.layers.Dense(256, activation=tf.nn.relu))
#model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
#model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(7, activation=tf.nn.softmax))

#tf.keras.optimizers.Optimizer
#optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
#optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
model.summary()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train,train_y_categorical, epochs=50, validation_data=(X_test ,test_y_categorical))

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_82 (Dense)            (None, 256)               5376

 normalization_7 (Normaliza  (None, 256)               513
 tion)

 dense_83 (Dense)            (None, 128)               32896

 dense_84 (Dense)            (None, 64)                8256

 dense_85 (Dense)            (None, 7)                 455

=================================================================
Total params: 47496 (185.54 KB)
Trainable params: 46983 (183.53 KB)
Non-trainable params: 513 (2.01 KB)
_________________________________________________________________
Epoch 1/50
519/519 [==============================] - 1s 1ms/step - loss: 1.2754 - accuracy: 0.5034 - val_loss: 0.8107 - val_accuracy: 0.6575
Epoch 2/50
519/519 [==============================] - 0s 899us/step - loss: 0.6874 - accuracy: 0.7203 - val_loss: 0.6549 - val_accuracy: 0.7389
Epoch 3/50
519/519 [==============================] - 0s 912us/step - loss: 0.6029 - accuracy: 0.7561 - val_loss: 0.5656 - val_accuracy: 0.7599
Epoch 4/50
519/519 [==============================] - 0s 917us/step - loss: 0.5459 - accuracy: 0.7836 - val_loss: 0.5082 - val_accuracy: 0.7972
Epoch 5/50
519/519 [==============================] - 0s 921us/step - loss: 0.4983 - accuracy: 0.8069 - val_loss: 0.4796 - val_accuracy: 0.8191
Epoch 6/50
519/519 [==============================] - 0s 924us/step - loss: 0.4890 - accuracy: 0.8146 - val_loss: 0.4650 - val_accuracy: 0.8239
Epoch 7/50
519/519 [==============================] - 0s 894us/step - loss: 0.4787 - accuracy: 0.8186 - val_loss: 0.4750 - val_accuracy: 0.8184
Epoch 8/50
519/519 [==============================] - 0s 911us/step - loss: 0.4704 - accuracy: 0.8213 - val_loss: 0.4538 - val_accuracy: 0.8343
Epoch 9/50
519/519 [==============================] - 0s 898us/step - loss: 0.4669 - accuracy: 0.8229 - val_loss: 0.4536 - val_accuracy: 0.8321
Epoch 10/50
519/519 [==============================] - 0s 908us/step - loss: 0.4643 - accuracy: 0.8252 - val_loss: 0.4567 - val_accuracy: 0.8324
Epoch 11/50
519/519 [==============================] - 0s 909us/step - loss: 0.4493 - accuracy: 0.8319 - val_loss: 0.4377 - val_accuracy: 0.8355
Epoch 12/50
519/519 [==============================] - 0s 933us/step - loss: 0.4433 - accuracy: 0.8321 - val_loss: 0.4305 - val_accuracy: 0.8386
Epoch 13/50
519/519 [==============================] - 0s 912us/step - loss: 0.4358 - accuracy: 0.8351 - val_loss: 0.4867 - val_accuracy: 0.8088
Epoch 14/50
519/519 [==============================] - 0s 902us/step - loss: 0.4337 - accuracy: 0.8382 - val_loss: 0.4352 - val_accuracy: 0.8386
Epoch 15/50
519/519 [==============================] - 0s 903us/step - loss: 0.4377 - accuracy: 0.8364 - val_loss: 0.4253 - val_accuracy: 0.8427
Epoch 16/50
519/519 [==============================] - 0s 908us/step - loss: 0.4268 - accuracy: 0.8389 - val_loss: 0.4100 - val_accuracy: 0.8495
Epoch 17/50
519/519 [==============================] - 0s 898us/step - loss: 0.4227 - accuracy: 0.8414 - val_loss: 0.4127 - val_accuracy: 0.8451
Epoch 18/50
519/519 [==============================] - 0s 911us/step - loss: 0.4244 - accuracy: 0.8372 - val_loss: 0.4185 - val_accuracy: 0.8379
Epoch 19/50
519/519 [==============================] - 0s 911us/step - loss: 0.4119 - accuracy: 0.8457 - val_loss: 0.4163 - val_accuracy: 0.8447
Epoch 20/50
519/519 [==============================] - 0s 908us/step - loss: 0.4093 - accuracy: 0.8470 - val_loss: 0.4242 - val_accuracy: 0.8415
Epoch 21/50
519/519 [==============================] - 0s 902us/step - loss: 0.4065 - accuracy: 0.8479 - val_loss: 0.3978 - val_accuracy: 0.8504
Epoch 22/50
519/519 [==============================] - 0s 918us/step - loss: 0.3999 - accuracy: 0.8510 - val_loss: 0.4132 - val_accuracy: 0.8444
Epoch 23/50
519/519 [==============================] - 0s 918us/step - loss: 0.4050 - accuracy: 0.8482 - val_loss: 0.4166 - val_accuracy: 0.8427
Epoch 24/50
519/519 [==============================] - 0s 924us/step - loss: 0.4001 - accuracy: 0.8517 - val_loss: 0.3996 - val_accuracy: 0.8504
Epoch 25/50
519/519 [==============================] - 0s 940us/step - loss: 0.4036 - accuracy: 0.8516 - val_loss: 0.4163 - val_accuracy: 0.8463
Epoch 26/50
519/519 [==============================] - 0s 925us/step - loss: 0.3942 - accuracy: 0.8529 - val_loss: 0.4003 - val_accuracy: 0.8565
Epoch 27/50
519/519 [==============================] - 0s 902us/step - loss: 0.3864 - accuracy: 0.8570 - val_loss: 0.4574 - val_accuracy: 0.8295
Epoch 28/50
519/519 [==============================] - 0s 895us/step - loss: 0.3905 - accuracy: 0.8558 - val_loss: 0.3923 - val_accuracy: 0.8543
Epoch 29/50
519/519 [==============================] - 0s 893us/step - loss: 0.3832 - accuracy: 0.8563 - val_loss: 0.4119 - val_accuracy: 0.8439
Epoch 30/50
519/519 [==============================] - 0s 899us/step - loss: 0.3792 - accuracy: 0.8586 - val_loss: 0.3838 - val_accuracy: 0.8548
Epoch 31/50
519/519 [==============================] - 0s 914us/step - loss: 0.3822 - accuracy: 0.8579 - val_loss: 0.4054 - val_accuracy: 0.8485
Epoch 32/50
519/519 [==============================] - 0s 906us/step - loss: 0.3768 - accuracy: 0.8600 - val_loss: 0.3899 - val_accuracy: 0.8500
Epoch 33/50
519/519 [==============================] - 0s 916us/step - loss: 0.3851 - accuracy: 0.8576 - val_loss: 0.4004 - val_accuracy: 0.8512
Epoch 34/50
519/519 [==============================] - 0s 911us/step - loss: 0.3770 - accuracy: 0.8575 - val_loss: 0.4035 - val_accuracy: 0.8456
Epoch 35/50
519/519 [==============================] - 0s 912us/step - loss: 0.3753 - accuracy: 0.8591 - val_loss: 0.3842 - val_accuracy: 0.8548
Epoch 36/50
519/519 [==============================] - 0s 901us/step - loss: 0.3762 - accuracy: 0.8588 - val_loss: 0.4156 - val_accuracy: 0.8473
Epoch 37/50
519/519 [==============================] - 0s 913us/step - loss: 0.3733 - accuracy: 0.8606 - val_loss: 0.4096 - val_accuracy: 0.8425
Epoch 38/50
519/519 [==============================] - 0s 883us/step - loss: 0.3713 - accuracy: 0.8605 - val_loss: 0.3899 - val_accuracy: 0.8550
Epoch 39/50
519/519 [==============================] - 0s 896us/step - loss: 0.3732 - accuracy: 0.8594 - val_loss: 0.4273 - val_accuracy: 0.8422
Epoch 40/50
519/519 [==============================] - 0s 893us/step - loss: 0.3688 - accuracy: 0.8610 - val_loss: 0.3969 - val_accuracy: 0.8524
Epoch 41/50
519/519 [==============================] - 0s 891us/step - loss: 0.3675 - accuracy: 0.8619 - val_loss: 0.3917 - val_accuracy: 0.8536
Epoch 42/50
519/519 [==============================] - 0s 906us/step - loss: 0.3708 - accuracy: 0.8613 - val_loss: 0.4541 - val_accuracy: 0.8268
Epoch 43/50
519/519 [==============================] - 0s 917us/step - loss: 0.3643 - accuracy: 0.8655 - val_loss: 0.4058 - val_accuracy: 0.8475
Epoch 44/50
519/519 [==============================] - 0s 900us/step - loss: 0.3614 - accuracy: 0.8637 - val_loss: 0.3993 - val_accuracy: 0.8514
Epoch 45/50
519/519 [==============================] - 0s 898us/step - loss: 0.3582 - accuracy: 0.8689 - val_loss: 0.4011 - val_accuracy: 0.8497
Epoch 46/50
519/519 [==============================] - 0s 918us/step - loss: 0.3589 - accuracy: 0.8687 - val_loss: 0.3949 - val_accuracy: 0.8555
Epoch 47/50
519/519 [==============================] - 0s 912us/step - loss: 0.3585 - accuracy: 0.8666 - val_loss: 0.3983 - val_accuracy: 0.8548
Epoch 48/50
519/519 [==============================] - 0s 900us/step - loss: 0.3566 - accuracy: 0.8687 - val_loss: 0.4197 - val_accuracy: 0.8406
Epoch 49/50
519/519 [==============================] - 0s 897us/step - loss: 0.3608 - accuracy: 0.8640 - val_loss: 0.3867 - val_accuracy: 0.8531
Epoch 50/50
519/519 [==============================] - 0s 905us/step - loss: 0.3530 - accuracy: 0.8684 - val_loss: 0.3933 - val_accuracy: 0.8485

In [86]:
sample_solution['NObeyesdad'] = model.predict(test)
sample_solution['NObeyesdad'] = sample_solution['NObeyesdad'].apply(y_restringing)
sample_solution.to_csv('s4e2_attempt_2_dnn.csv', index=False)

433/433 [==============================] - 0s 571us/step

In [100]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import r2_score

In [135]:
import xgboost as xgb
booster = xgb.XGBClassifier(n_estimators=5000, #booster = 'gbtree', tree_method = 'hist', 
    objective='multi:softmax',
    num_classes = 7,
    max_depth = 5,
    learning_rate = 0.01,
    #num_parallel_tree = 1, process_type = 'default',
    #eval_metric= mean_squared_log_error,
    subsample = 0.7, #weird xgb dropout equivalent for prevention of overfitting
    #max_bin = 512, predictor = 'cpu_predictor'
    )

booster.fit(X_train, Y_train,eval_set=[(X_train, Y_train), (X_test, Y_test)],early_stopping_rounds= 200,verbose=True)

[0]	validation_0-mlogloss:1.92073	validation_1-mlogloss:1.92108

[1]	validation_0-mlogloss:1.89629	validation_1-mlogloss:1.89700
[2]	validation_0-mlogloss:1.87273	validation_1-mlogloss:1.87374
[3]	validation_0-mlogloss:1.84987	validation_1-mlogloss:1.85117
[4]	validation_0-mlogloss:1.82761	validation_1-mlogloss:1.82915
[5]	validation_0-mlogloss:1.80585	validation_1-mlogloss:1.80764
[6]	validation_0-mlogloss:1.78479	validation_1-mlogloss:1.78685
[7]	validation_0-mlogloss:1.76431	validation_1-mlogloss:1.76655
[8]	validation_0-mlogloss:1.74439	validation_1-mlogloss:1.74686
[9]	validation_0-mlogloss:1.72472	validation_1-mlogloss:1.72741
[10]	validation_0-mlogloss:1.70576	validation_1-mlogloss:1.70869
[11]	validation_0-mlogloss:1.68703	validation_1-mlogloss:1.69018
[12]	validation_0-mlogloss:1.66885	validation_1-mlogloss:1.67218
[13]	validation_0-mlogloss:1.65103	validation_1-mlogloss:1.65455
[14]	validation_0-mlogloss:1.63360	validation_1-mlogloss:1.63734
[15]	validation_0-mlogloss:1.61662	validation_1-mlogloss:1.62061
[16]	validation_0-mlogloss:1.59997	validation_1-mlogloss:1.60416
[17]	validation_0-mlogloss:1.58372	validation_1-mlogloss:1.58807
[18]	validation_0-mlogloss:1.56770	validation_1-mlogloss:1.57219
[19]	validation_0-mlogloss:1.55207	validation_1-mlogloss:1.55676
[20]	validation_0-mlogloss:1.53680	validation_1-mlogloss:1.54167
[21]	validation_0-mlogloss:1.52171	validation_1-mlogloss:1.52675
[22]	validation_0-mlogloss:1.50700	validation_1-mlogloss:1.51218
[23]	validation_0-mlogloss:1.49274	validation_1-mlogloss:1.49812
[24]	validation_0-mlogloss:1.47876	validation_1-mlogloss:1.48433
[25]	validation_0-mlogloss:1.46471	validation_1-mlogloss:1.47042
[26]	validation_0-mlogloss:1.45110	validation_1-mlogloss:1.45699

c:\Users\steph\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
c:\Users\steph\anaconda3\Lib\site-packages\xgboost\core.py:160: UserWarning: [10:52:56] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742:
Parameters: { "num_classes" } are not used.

  warnings.warn(smsg, UserWarning)

[27]	validation_0-mlogloss:1.43757	validation_1-mlogloss:1.44362
[28]	validation_0-mlogloss:1.42428	validation_1-mlogloss:1.43055
[29]	validation_0-mlogloss:1.41142	validation_1-mlogloss:1.41785
[30]	validation_0-mlogloss:1.39870	validation_1-mlogloss:1.40532
[31]	validation_0-mlogloss:1.38632	validation_1-mlogloss:1.39308
[32]	validation_0-mlogloss:1.37384	validation_1-mlogloss:1.38071
[33]	validation_0-mlogloss:1.36178	validation_1-mlogloss:1.36876
[34]	validation_0-mlogloss:1.34976	validation_1-mlogloss:1.35678
[35]	validation_0-mlogloss:1.33817	validation_1-mlogloss:1.34530
[36]	validation_0-mlogloss:1.32668	validation_1-mlogloss:1.33392
[37]	validation_0-mlogloss:1.31542	validation_1-mlogloss:1.32283
[38]	validation_0-mlogloss:1.30437	validation_1-mlogloss:1.31197
[39]	validation_0-mlogloss:1.29343	validation_1-mlogloss:1.30122
[40]	validation_0-mlogloss:1.28264	validation_1-mlogloss:1.29057
[41]	validation_0-mlogloss:1.27203	validation_1-mlogloss:1.28014
[42]	validation_0-mlogloss:1.26155	validation_1-mlogloss:1.26979
[43]	validation_0-mlogloss:1.25140	validation_1-mlogloss:1.25985
[44]	validation_0-mlogloss:1.24136	validation_1-mlogloss:1.24987
[45]	validation_0-mlogloss:1.23133	validation_1-mlogloss:1.23998
[46]	validation_0-mlogloss:1.22152	validation_1-mlogloss:1.23036
[47]	validation_0-mlogloss:1.21210	validation_1-mlogloss:1.22108
[48]	validation_0-mlogloss:1.20249	validation_1-mlogloss:1.21157
[49]	validation_0-mlogloss:1.19293	validation_1-mlogloss:1.20208
[50]	validation_0-mlogloss:1.18362	validation_1-mlogloss:1.19292
[51]	validation_0-mlogloss:1.17436	validation_1-mlogloss:1.18378
[52]	validation_0-mlogloss:1.16513	validation_1-mlogloss:1.17467
[53]	validation_0-mlogloss:1.15621	validation_1-mlogloss:1.16582
[54]	validation_0-mlogloss:1.14741	validation_1-mlogloss:1.15712
[55]	validation_0-mlogloss:1.13871	validation_1-mlogloss:1.14853
[56]	validation_0-mlogloss:1.13002	validation_1-mlogloss:1.13990
[57]	validation_0-mlogloss:1.12173	validation_1-mlogloss:1.13172
[58]	validation_0-mlogloss:1.11337	validation_1-mlogloss:1.12348
[59]	validation_0-mlogloss:1.10528	validation_1-mlogloss:1.11553
[60]	validation_0-mlogloss:1.09738	validation_1-mlogloss:1.10780
[61]	validation_0-mlogloss:1.08957	validation_1-mlogloss:1.10013
[62]	validation_0-mlogloss:1.08172	validation_1-mlogloss:1.09243
[63]	validation_0-mlogloss:1.07393	validation_1-mlogloss:1.08476
[64]	validation_0-mlogloss:1.06645	validation_1-mlogloss:1.07746
[65]	validation_0-mlogloss:1.05898	validation_1-mlogloss:1.07010
[66]	validation_0-mlogloss:1.05166	validation_1-mlogloss:1.06292
[67]	validation_0-mlogloss:1.04443	validation_1-mlogloss:1.05585
[68]	validation_0-mlogloss:1.03705	validation_1-mlogloss:1.04860
[69]	validation_0-mlogloss:1.02997	validation_1-mlogloss:1.04170
[70]	validation_0-mlogloss:1.02282	validation_1-mlogloss:1.03467
[71]	validation_0-mlogloss:1.01574	validation_1-mlogloss:1.02769
[72]	validation_0-mlogloss:1.00888	validation_1-mlogloss:1.02095
[73]	validation_0-mlogloss:1.00225	validation_1-mlogloss:1.01448
[74]	validation_0-mlogloss:0.99556	validation_1-mlogloss:1.00792
[75]	validation_0-mlogloss:0.98892	validation_1-mlogloss:1.00144
[76]	validation_0-mlogloss:0.98231	validation_1-mlogloss:0.99499
[77]	validation_0-mlogloss:0.97576	validation_1-mlogloss:0.98852
[78]	validation_0-mlogloss:0.96917	validation_1-mlogloss:0.98200
[79]	validation_0-mlogloss:0.96289	validation_1-mlogloss:0.97583
[80]	validation_0-mlogloss:0.95674	validation_1-mlogloss:0.96983
[81]	validation_0-mlogloss:0.95054	validation_1-mlogloss:0.96371
[82]	validation_0-mlogloss:0.94452	validation_1-mlogloss:0.95786
[83]	validation_0-mlogloss:0.93811	validation_1-mlogloss:0.95156
[84]	validation_0-mlogloss:0.93213	validation_1-mlogloss:0.94568
[85]	validation_0-mlogloss:0.92617	validation_1-mlogloss:0.93984
[86]	validation_0-mlogloss:0.92023	validation_1-mlogloss:0.93402
[87]	validation_0-mlogloss:0.91441	validation_1-mlogloss:0.92827
[88]	validation_0-mlogloss:0.90864	validation_1-mlogloss:0.92263
[89]	validation_0-mlogloss:0.90298	validation_1-mlogloss:0.91709
[90]	validation_0-mlogloss:0.89737	validation_1-mlogloss:0.91160
[91]	validation_0-mlogloss:0.89198	validation_1-mlogloss:0.90634
[92]	validation_0-mlogloss:0.88651	validation_1-mlogloss:0.90098
[93]	validation_0-mlogloss:0.88110	validation_1-mlogloss:0.89568
[94]	validation_0-mlogloss:0.87559	validation_1-mlogloss:0.89030
[95]	validation_0-mlogloss:0.87004	validation_1-mlogloss:0.88485
[96]	validation_0-mlogloss:0.86483	validation_1-mlogloss:0.87980
[97]	validation_0-mlogloss:0.85955	validation_1-mlogloss:0.87464
[98]	validation_0-mlogloss:0.85424	validation_1-mlogloss:0.86943
[99]	validation_0-mlogloss:0.84921	validation_1-mlogloss:0.86452
[100]	validation_0-mlogloss:0.84415	validation_1-mlogloss:0.85957
[101]	validation_0-mlogloss:0.83916	validation_1-mlogloss:0.85471
[102]	validation_0-mlogloss:0.83411	validation_1-mlogloss:0.84980
[103]	validation_0-mlogloss:0.82920	validation_1-mlogloss:0.84499
[104]	validation_0-mlogloss:0.82422	validation_1-mlogloss:0.84011
[105]	validation_0-mlogloss:0.81944	validation_1-mlogloss:0.83548
[106]	validation_0-mlogloss:0.81467	validation_1-mlogloss:0.83081
[107]	validation_0-mlogloss:0.81002	validation_1-mlogloss:0.82633
[108]	validation_0-mlogloss:0.80556	validation_1-mlogloss:0.82198
[109]	validation_0-mlogloss:0.80097	validation_1-mlogloss:0.81750
[110]	validation_0-mlogloss:0.79633	validation_1-mlogloss:0.81296
[111]	validation_0-mlogloss:0.79189	validation_1-mlogloss:0.80870
[112]	validation_0-mlogloss:0.78747	validation_1-mlogloss:0.80443
[113]	validation_0-mlogloss:0.78299	validation_1-mlogloss:0.80005
[114]	validation_0-mlogloss:0.77860	validation_1-mlogloss:0.79576
[115]	validation_0-mlogloss:0.77429	validation_1-mlogloss:0.79159
[116]	validation_0-mlogloss:0.76996	validation_1-mlogloss:0.78737
[117]	validation_0-mlogloss:0.76577	validation_1-mlogloss:0.78332
[118]	validation_0-mlogloss:0.76167	validation_1-mlogloss:0.77932
[119]	validation_0-mlogloss:0.75758	validation_1-mlogloss:0.77536
[120]	validation_0-mlogloss:0.75339	validation_1-mlogloss:0.77127
[121]	validation_0-mlogloss:0.74922	validation_1-mlogloss:0.76716
[122]	validation_0-mlogloss:0.74525	validation_1-mlogloss:0.76329
[123]	validation_0-mlogloss:0.74133	validation_1-mlogloss:0.75947
[124]	validation_0-mlogloss:0.73732	validation_1-mlogloss:0.75560
[125]	validation_0-mlogloss:0.73339	validation_1-mlogloss:0.75176
[126]	validation_0-mlogloss:0.72962	validation_1-mlogloss:0.74810
[127]	validation_0-mlogloss:0.72570	validation_1-mlogloss:0.74434
[128]	validation_0-mlogloss:0.72184	validation_1-mlogloss:0.74064
[129]	validation_0-mlogloss:0.71813	validation_1-mlogloss:0.73701
[130]	validation_0-mlogloss:0.71439	validation_1-mlogloss:0.73338
[131]	validation_0-mlogloss:0.71077	validation_1-mlogloss:0.72991
[132]	validation_0-mlogloss:0.70715	validation_1-mlogloss:0.72637
[133]	validation_0-mlogloss:0.70356	validation_1-mlogloss:0.72290
[134]	validation_0-mlogloss:0.69998	validation_1-mlogloss:0.71946
[135]	validation_0-mlogloss:0.69643	validation_1-mlogloss:0.71597
[136]	validation_0-mlogloss:0.69293	validation_1-mlogloss:0.71260
[137]	validation_0-mlogloss:0.68944	validation_1-mlogloss:0.70920
[138]	validation_0-mlogloss:0.68597	validation_1-mlogloss:0.70584
[139]	validation_0-mlogloss:0.68254	validation_1-mlogloss:0.70252
[140]	validation_0-mlogloss:0.67911	validation_1-mlogloss:0.69920
[141]	validation_0-mlogloss:0.67576	validation_1-mlogloss:0.69596
[142]	validation_0-mlogloss:0.67245	validation_1-mlogloss:0.69276
[143]	validation_0-mlogloss:0.66912	validation_1-mlogloss:0.68951
[144]	validation_0-mlogloss:0.66580	validation_1-mlogloss:0.68632
[145]	validation_0-mlogloss:0.66263	validation_1-mlogloss:0.68326
[146]	validation_0-mlogloss:0.65946	validation_1-mlogloss:0.68017
[147]	validation_0-mlogloss:0.65629	validation_1-mlogloss:0.67710
[148]	validation_0-mlogloss:0.65314	validation_1-mlogloss:0.67406
[149]	validation_0-mlogloss:0.64999	validation_1-mlogloss:0.67102
[150]	validation_0-mlogloss:0.64691	validation_1-mlogloss:0.66805
[151]	validation_0-mlogloss:0.64386	validation_1-mlogloss:0.66508
[152]	validation_0-mlogloss:0.64084	validation_1-mlogloss:0.66217
[153]	validation_0-mlogloss:0.63786	validation_1-mlogloss:0.65931
[154]	validation_0-mlogloss:0.63488	validation_1-mlogloss:0.65643
[155]	validation_0-mlogloss:0.63195	validation_1-mlogloss:0.65361
[156]	validation_0-mlogloss:0.62906	validation_1-mlogloss:0.65079
[157]	validation_0-mlogloss:0.62602	validation_1-mlogloss:0.64781
[158]	validation_0-mlogloss:0.62319	validation_1-mlogloss:0.64509
[159]	validation_0-mlogloss:0.62038	validation_1-mlogloss:0.64240
[160]	validation_0-mlogloss:0.61758	validation_1-mlogloss:0.63971
[161]	validation_0-mlogloss:0.61477	validation_1-mlogloss:0.63700
[162]	validation_0-mlogloss:0.61206	validation_1-mlogloss:0.63438
[163]	validation_0-mlogloss:0.60926	validation_1-mlogloss:0.63169
[164]	validation_0-mlogloss:0.60662	validation_1-mlogloss:0.62912
[165]	validation_0-mlogloss:0.60395	validation_1-mlogloss:0.62656
[166]	validation_0-mlogloss:0.60132	validation_1-mlogloss:0.62403
[167]	validation_0-mlogloss:0.59877	validation_1-mlogloss:0.62156
[168]	validation_0-mlogloss:0.59617	validation_1-mlogloss:0.61907
[169]	validation_0-mlogloss:0.59361	validation_1-mlogloss:0.61662
[170]	validation_0-mlogloss:0.59113	validation_1-mlogloss:0.61424
[171]	validation_0-mlogloss:0.58856	validation_1-mlogloss:0.61175
[172]	validation_0-mlogloss:0.58601	validation_1-mlogloss:0.60933
[173]	validation_0-mlogloss:0.58357	validation_1-mlogloss:0.60698
[174]	validation_0-mlogloss:0.58108	validation_1-mlogloss:0.60459
[175]	validation_0-mlogloss:0.57861	validation_1-mlogloss:0.60220
[176]	validation_0-mlogloss:0.57612	validation_1-mlogloss:0.59981
[177]	validation_0-mlogloss:0.57372	validation_1-mlogloss:0.59751
[178]	validation_0-mlogloss:0.57138	validation_1-mlogloss:0.59527
[179]	validation_0-mlogloss:0.56907	validation_1-mlogloss:0.59308
[180]	validation_0-mlogloss:0.56677	validation_1-mlogloss:0.59089
[181]	validation_0-mlogloss:0.56447	validation_1-mlogloss:0.58870
[182]	validation_0-mlogloss:0.56224	validation_1-mlogloss:0.58655
[183]	validation_0-mlogloss:0.56001	validation_1-mlogloss:0.58441
[184]	validation_0-mlogloss:0.55774	validation_1-mlogloss:0.58221
[185]	validation_0-mlogloss:0.55548	validation_1-mlogloss:0.58002
[186]	validation_0-mlogloss:0.55323	validation_1-mlogloss:0.57790
[187]	validation_0-mlogloss:0.55101	validation_1-mlogloss:0.57579
[188]	validation_0-mlogloss:0.54891	validation_1-mlogloss:0.57382
[189]	validation_0-mlogloss:0.54674	validation_1-mlogloss:0.57176
[190]	validation_0-mlogloss:0.54456	validation_1-mlogloss:0.56966
[191]	validation_0-mlogloss:0.54248	validation_1-mlogloss:0.56769
[192]	validation_0-mlogloss:0.54042	validation_1-mlogloss:0.56573
[193]	validation_0-mlogloss:0.53834	validation_1-mlogloss:0.56376
[194]	validation_0-mlogloss:0.53626	validation_1-mlogloss:0.56176
[195]	validation_0-mlogloss:0.53424	validation_1-mlogloss:0.55984
[196]	validation_0-mlogloss:0.53223	validation_1-mlogloss:0.55791
[197]	validation_0-mlogloss:0.53022	validation_1-mlogloss:0.55597
[198]	validation_0-mlogloss:0.52824	validation_1-mlogloss:0.55412
[199]	validation_0-mlogloss:0.52621	validation_1-mlogloss:0.55218
[200]	validation_0-mlogloss:0.52424	validation_1-mlogloss:0.55030
[201]	validation_0-mlogloss:0.52222	validation_1-mlogloss:0.54836
[202]	validation_0-mlogloss:0.52017	validation_1-mlogloss:0.54639
[203]	validation_0-mlogloss:0.51828	validation_1-mlogloss:0.54460
[204]	validation_0-mlogloss:0.51638	validation_1-mlogloss:0.54281
[205]	validation_0-mlogloss:0.51446	validation_1-mlogloss:0.54097
[206]	validation_0-mlogloss:0.51260	validation_1-mlogloss:0.53919
[207]	validation_0-mlogloss:0.51071	validation_1-mlogloss:0.53738
[208]	validation_0-mlogloss:0.50879	validation_1-mlogloss:0.53550
[209]	validation_0-mlogloss:0.50693	validation_1-mlogloss:0.53377
[210]	validation_0-mlogloss:0.50516	validation_1-mlogloss:0.53209
[211]	validation_0-mlogloss:0.50339	validation_1-mlogloss:0.53041
[212]	validation_0-mlogloss:0.50156	validation_1-mlogloss:0.52864
[213]	validation_0-mlogloss:0.49978	validation_1-mlogloss:0.52696
[214]	validation_0-mlogloss:0.49811	validation_1-mlogloss:0.52538
[215]	validation_0-mlogloss:0.49644	validation_1-mlogloss:0.52380
[216]	validation_0-mlogloss:0.49471	validation_1-mlogloss:0.52215
[217]	validation_0-mlogloss:0.49301	validation_1-mlogloss:0.52055
[218]	validation_0-mlogloss:0.49120	validation_1-mlogloss:0.51879
[219]	validation_0-mlogloss:0.48938	validation_1-mlogloss:0.51706
[220]	validation_0-mlogloss:0.48776	validation_1-mlogloss:0.51553
[221]	validation_0-mlogloss:0.48610	validation_1-mlogloss:0.51396
[222]	validation_0-mlogloss:0.48437	validation_1-mlogloss:0.51232
[223]	validation_0-mlogloss:0.48271	validation_1-mlogloss:0.51075
[224]	validation_0-mlogloss:0.48115	validation_1-mlogloss:0.50930
[225]	validation_0-mlogloss:0.47948	validation_1-mlogloss:0.50769
[226]	validation_0-mlogloss:0.47790	validation_1-mlogloss:0.50623
[227]	validation_0-mlogloss:0.47640	validation_1-mlogloss:0.50478
[228]	validation_0-mlogloss:0.47471	validation_1-mlogloss:0.50317
[229]	validation_0-mlogloss:0.47319	validation_1-mlogloss:0.50173
[230]	validation_0-mlogloss:0.47167	validation_1-mlogloss:0.50032
[231]	validation_0-mlogloss:0.47020	validation_1-mlogloss:0.49892
[232]	validation_0-mlogloss:0.46860	validation_1-mlogloss:0.49740
[233]	validation_0-mlogloss:0.46699	validation_1-mlogloss:0.49586
[234]	validation_0-mlogloss:0.46553	validation_1-mlogloss:0.49448
[235]	validation_0-mlogloss:0.46394	validation_1-mlogloss:0.49294
[236]	validation_0-mlogloss:0.46245	validation_1-mlogloss:0.49155
[237]	validation_0-mlogloss:0.46098	validation_1-mlogloss:0.49019
[238]	validation_0-mlogloss:0.45954	validation_1-mlogloss:0.48882
[239]	validation_0-mlogloss:0.45806	validation_1-mlogloss:0.48743
[240]	validation_0-mlogloss:0.45662	validation_1-mlogloss:0.48608
[241]	validation_0-mlogloss:0.45528	validation_1-mlogloss:0.48480
[242]	validation_0-mlogloss:0.45376	validation_1-mlogloss:0.48335
[243]	validation_0-mlogloss:0.45238	validation_1-mlogloss:0.48206
[244]	validation_0-mlogloss:0.45087	validation_1-mlogloss:0.48061
[245]	validation_0-mlogloss:0.44951	validation_1-mlogloss:0.47934
[246]	validation_0-mlogloss:0.44810	validation_1-mlogloss:0.47799
[247]	validation_0-mlogloss:0.44676	validation_1-mlogloss:0.47672
[248]	validation_0-mlogloss:0.44531	validation_1-mlogloss:0.47533
[249]	validation_0-mlogloss:0.44400	validation_1-mlogloss:0.47409
[250]	validation_0-mlogloss:0.44265	validation_1-mlogloss:0.47284
[251]	validation_0-mlogloss:0.44134	validation_1-mlogloss:0.47160
[252]	validation_0-mlogloss:0.44008	validation_1-mlogloss:0.47043
[253]	validation_0-mlogloss:0.43881	validation_1-mlogloss:0.46926
[254]	validation_0-mlogloss:0.43754	validation_1-mlogloss:0.46811
[255]	validation_0-mlogloss:0.43634	validation_1-mlogloss:0.46698
[256]	validation_0-mlogloss:0.43513	validation_1-mlogloss:0.46582
[257]	validation_0-mlogloss:0.43383	validation_1-mlogloss:0.46459
[258]	validation_0-mlogloss:0.43257	validation_1-mlogloss:0.46340
[259]	validation_0-mlogloss:0.43126	validation_1-mlogloss:0.46216
[260]	validation_0-mlogloss:0.43006	validation_1-mlogloss:0.46105
[261]	validation_0-mlogloss:0.42892	validation_1-mlogloss:0.45998
[262]	validation_0-mlogloss:0.42781	validation_1-mlogloss:0.45891
[263]	validation_0-mlogloss:0.42656	validation_1-mlogloss:0.45772
[264]	validation_0-mlogloss:0.42537	validation_1-mlogloss:0.45661
[265]	validation_0-mlogloss:0.42427	validation_1-mlogloss:0.45559
[266]	validation_0-mlogloss:0.42309	validation_1-mlogloss:0.45447
[267]	validation_0-mlogloss:0.42195	validation_1-mlogloss:0.45341
[268]	validation_0-mlogloss:0.42085	validation_1-mlogloss:0.45239
[269]	validation_0-mlogloss:0.41971	validation_1-mlogloss:0.45131
[270]	validation_0-mlogloss:0.41861	validation_1-mlogloss:0.45027
[271]	validation_0-mlogloss:0.41733	validation_1-mlogloss:0.44908
[272]	validation_0-mlogloss:0.41624	validation_1-mlogloss:0.44808
[273]	validation_0-mlogloss:0.41513	validation_1-mlogloss:0.44707
[274]	validation_0-mlogloss:0.41403	validation_1-mlogloss:0.44605
[275]	validation_0-mlogloss:0.41289	validation_1-mlogloss:0.44496
[276]	validation_0-mlogloss:0.41185	validation_1-mlogloss:0.44400
[277]	validation_0-mlogloss:0.41080	validation_1-mlogloss:0.44303
[278]	validation_0-mlogloss:0.40978	validation_1-mlogloss:0.44210
[279]	validation_0-mlogloss:0.40873	validation_1-mlogloss:0.44112
[280]	validation_0-mlogloss:0.40759	validation_1-mlogloss:0.44003
[281]	validation_0-mlogloss:0.40656	validation_1-mlogloss:0.43906
[282]	validation_0-mlogloss:0.40549	validation_1-mlogloss:0.43802
[283]	validation_0-mlogloss:0.40447	validation_1-mlogloss:0.43704
[284]	validation_0-mlogloss:0.40342	validation_1-mlogloss:0.43609
[285]	validation_0-mlogloss:0.40242	validation_1-mlogloss:0.43517
[286]	validation_0-mlogloss:0.40146	validation_1-mlogloss:0.43431
[287]	validation_0-mlogloss:0.40042	validation_1-mlogloss:0.43335
[288]	validation_0-mlogloss:0.39935	validation_1-mlogloss:0.43233
[289]	validation_0-mlogloss:0.39835	validation_1-mlogloss:0.43140
[290]	validation_0-mlogloss:0.39740	validation_1-mlogloss:0.43051
[291]	validation_0-mlogloss:0.39645	validation_1-mlogloss:0.42962
[292]	validation_0-mlogloss:0.39536	validation_1-mlogloss:0.42860
[293]	validation_0-mlogloss:0.39444	validation_1-mlogloss:0.42777
[294]	validation_0-mlogloss:0.39344	validation_1-mlogloss:0.42688
[295]	validation_0-mlogloss:0.39251	validation_1-mlogloss:0.42603
[296]	validation_0-mlogloss:0.39153	validation_1-mlogloss:0.42514
[297]	validation_0-mlogloss:0.39060	validation_1-mlogloss:0.42430
[298]	validation_0-mlogloss:0.38971	validation_1-mlogloss:0.42348
[299]	validation_0-mlogloss:0.38883	validation_1-mlogloss:0.42267
[300]	validation_0-mlogloss:0.38790	validation_1-mlogloss:0.42181
[301]	validation_0-mlogloss:0.38705	validation_1-mlogloss:0.42103
[302]	validation_0-mlogloss:0.38612	validation_1-mlogloss:0.42018
[303]	validation_0-mlogloss:0.38529	validation_1-mlogloss:0.41939
[304]	validation_0-mlogloss:0.38447	validation_1-mlogloss:0.41866
[305]	validation_0-mlogloss:0.38357	validation_1-mlogloss:0.41784
[306]	validation_0-mlogloss:0.38266	validation_1-mlogloss:0.41701
[307]	validation_0-mlogloss:0.38180	validation_1-mlogloss:0.41623
[308]	validation_0-mlogloss:0.38095	validation_1-mlogloss:0.41544
[309]	validation_0-mlogloss:0.38013	validation_1-mlogloss:0.41467
[310]	validation_0-mlogloss:0.37929	validation_1-mlogloss:0.41391
[311]	validation_0-mlogloss:0.37846	validation_1-mlogloss:0.41316
[312]	validation_0-mlogloss:0.37765	validation_1-mlogloss:0.41241
[313]	validation_0-mlogloss:0.37683	validation_1-mlogloss:0.41167
[314]	validation_0-mlogloss:0.37600	validation_1-mlogloss:0.41089
[315]	validation_0-mlogloss:0.37517	validation_1-mlogloss:0.41010
[316]	validation_0-mlogloss:0.37433	validation_1-mlogloss:0.40931
[317]	validation_0-mlogloss:0.37354	validation_1-mlogloss:0.40857
[318]	validation_0-mlogloss:0.37273	validation_1-mlogloss:0.40780
[319]	validation_0-mlogloss:0.37192	validation_1-mlogloss:0.40708
[320]	validation_0-mlogloss:0.37100	validation_1-mlogloss:0.40623
[321]	validation_0-mlogloss:0.37024	validation_1-mlogloss:0.40552
[322]	validation_0-mlogloss:0.36938	validation_1-mlogloss:0.40471
[323]	validation_0-mlogloss:0.36862	validation_1-mlogloss:0.40403
[324]	validation_0-mlogloss:0.36789	validation_1-mlogloss:0.40336
[325]	validation_0-mlogloss:0.36713	validation_1-mlogloss:0.40270
[326]	validation_0-mlogloss:0.36640	validation_1-mlogloss:0.40207
[327]	validation_0-mlogloss:0.36560	validation_1-mlogloss:0.40134
[328]	validation_0-mlogloss:0.36480	validation_1-mlogloss:0.40060
[329]	validation_0-mlogloss:0.36405	validation_1-mlogloss:0.39993
[330]	validation_0-mlogloss:0.36334	validation_1-mlogloss:0.39930

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=5000, n_jobs=None,
              num_classes=7, num_parallel_tree=None, ...)

In [136]:
sample_solution['NObeyesdad'] = booster.predict(test)
sample_solution['NObeyesdad'] = sample_solution['NObeyesdad'].apply(y_restringing)
sample_solution.to_csv('s4e2_attempt_5_xgb.csv', index=False)